// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoUAGaee0Xnoeezm2YTmwACg85Ja8LBcY',
    appId: '1:866670045570:ios:39e0635fc072e9f7cf479b',
    messagingSenderId: '866670045570',
    projectId: 'luggease-89d1f',
    storageBucket: 'luggease-89d1f.firebasestorage.app',
    iosBundleId: 'com.example.luggease',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3-ojAA__wsCJI3EcTJ61h2ayRHhUYoy0',
    appId: '1:866670045570:web:c31f1e78153844cfcf479b',
    messagingSenderId: '866670045570',
    projectId: 'luggease-89d1f',
    authDomain: 'luggease-89d1f.firebaseapp.com',
    storageBucket: 'luggease-89d1f.firebasestorage.app',
    measurementId: 'G-22CWLD71X4',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoUAGaee0Xnoeezm2YTmwACg85Ja8LBcY',
    appId: '1:866670045570:ios:99c77346bd8145cfcf479b',
    messagingSenderId: '866670045570',
    projectId: 'luggease-89d1f',
    storageBucket: 'luggease-89d1f.firebasestorage.app',
    iosBundleId: 'com.luggease.luggease',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyBfnMrrRi1FrN7yq4ZWQIX1MMoaPB3WE',
    appId: '1:866670045570:android:341e5ba152333ea4cf479b',
    messagingSenderId: '866670045570',
    projectId: 'luggease-89d1f',
    storageBucket: 'luggease-89d1f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3-ojAA__wsCJI3EcTJ61h2ayRHhUYoy0',
    appId: '1:866670045570:web:793838d0b888a3fecf479b',
    messagingSenderId: '866670045570',
    projectId: 'luggease-89d1f',
    authDomain: 'luggease-89d1f.firebaseapp.com',
    storageBucket: 'luggease-89d1f.firebasestorage.app',
    measurementId: 'G-1TXX57NMQ4',
  );

}